# Generated by Django 2.2.4 on 2019-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=64)),
                ('classname', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='versions',
        ),
    ]
