# Generated by Django 2.2.4 on 2019-11-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191002_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=64)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.classes')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, null=True)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.classes')),
            ],
        ),
    ]
