# Generated by Django 2.2.4 on 2019-11-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_imagesurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagesUrl',
        ),
    ]
