# Generated by Django 2.2.4 on 2019-11-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_delete_imagesurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=64)),
            ],
        ),
    ]
